"""
This module contains constants used in the application.
"""

# HTTP methods
GET = "GET"
POST = "POST"
PUT = "PUT"
DELETE = "DELETE"

# Email related variables
GOOGLE_ACCOUNT_BOT_EMAIL_ENV_VAR = "GOOGLE_ACCOUNT_BOT_EMAIL"
GOOGLE_ACCOUNT_BOT_PASSWORD_ENV_VAR = "GOOGLE_ACCOUNT_BOT_PASSWORD"
GOOGLE_ACCOUNT_PERSONAL_EMAIL_ENV_VAR = "GOOGLE_ACCOUNT_PERSONAL_EMAIL"
